<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SampleSales.Application/SampleSales.Application.csproj" />
    <ProjectReference Include="../SampleSales.Domain/SampleSales.Domain.csproj" />
  </ItemGroup>
</Project>
